#!/bin/sh

# This file is executed by greetd, the purpose of which is to set a bunch of env vars
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix sway display flickering
# Defaults to gles2, vulkan temporarily fixes flickering
# in games like Counter-Strike 2
export WLR_RENDERER=vulkan

exec dbus-run-session sway "$@"
