#!/bin/sh
# https://www.shellcheck.net/wiki/SC2034
# shellcheck disable=2034

swaymsg -t subscribe -m '["window"]' | while read -r line ;  do
    count=$(swaymsg -t get_tree | jq '.nodes[].nodes[] | select(.name == "__i3_scratch") | .focus | length')

    if [ "$count" -gt 0 ]; then
        printf "%s\n" "S: ${count}"
    else
        printf "%s\n" ""
    fi
done
